apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyterhub-jopa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyterhub-jopa
    spec:
      containers:
      - name: hub
        image: jopa/jupyterhub
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-web
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30300
  selector:
    app: jupyterhub-jopa
