apiVersion: v1
kind: Pod
metadata:
  name: gluster-02
  labels:
    name: gluster-02
spec:
  hostNetwork: true
  nodeSelector:
    name: kube-02
  containers:
    - name: glusterfs
      image: gluster/rhgs-3.1.0
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
          - name: brickpath
            mountPath: "/mnt/brick1"
      securityContext: 
       capabilities: {}
       privileged: true
  volumes:
    - name: brickpath
      hostPath:
        path: "/mnt/brick1"

